language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "6"
  - "node"

script:
  - hexo generate
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
