language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "10"

script:
  - hexo generate
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master
